### ISSUE TITLE
Theme change is not saved

### ISSUE THREAD

**Issue by JBMEIZO** [go-vikunja/frontend#105]
### Description

As soon as I change the color scheme from light to dark under the settings for my user, the color scheme changes as desired and the entire frontend is displayed dark.
After I logout and reload the page in my browser the color scheme adjustment is back to the old state. The settings in the profile regarding the color scheme are not saved.

### Vikunja Frontend Version

0.20.3

### Vikunja API Version

0.20.2

### Browser and version

Brave: Version 1.48.164 Chromium: 110.0.5481.100

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by vinaykapadia** [comment]
At a minimum, just for now, is there a way to have the default be dark mode? Users can change it if they want, just like they can now. But all my users want dark any way.

**Comment by kolaente** [comment]
Right now there's no way to make dark mode a default. The theme settings respects the system's preference for dark mode though, so if your users all want dark mode they should set it in their browser's settings accordingly.

**Comment by jamescochran** [comment]
Sorry to beat a dead horse here but I was trying to figure this out and found this thread. My system (macOS 11) as well as browser (Firefox 117.0.1) are both set to dark mode yet Vikunja switches to light mode all the time. Should I bother making a new issue for that or just wait until Vikunja is updated to store this server side?

**Comment by kolaente** [comment]
@jamescochran which version are you using? Can you reproduce this on [try](https://try.vikunja.io)?
