### ISSUE TITLE
macOS auto-correct takes over in assignee input box

### ISSUE THREAD

**Issue by rdbell** [go-vikunja/frontend#114]
### Description

I'm not sure exactly what the conditions are to trigger this, but occasionally when I type my username in the assignee field `rdbell` gets autocorrected to `robell`

I assume adding `autocorrect="off" spellcheck="false"` to the assignee input field should fix the problem.

### Vikunja Frontend Version

vikunja/frontend:unstable

### Vikunja API Version

vikunja/api:unstable

### Browser and version

MenubarX (safari?)

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Should be fixed in 64f9f4fd88a513cbc401aacbeab87695bb9f55bf - please check with the next unstable build (for example on [try](https://try.vikunja.io) in ~40min when the CI released a new build. Please also make sure to clear your browser cache or use a private window to avoid caching issues.

**Comment by rdbell** [comment]
Hi @kolaente,

Just noticed this also happens with the username in the login form.

Thanks for the quick responses! Really impressed with your project.
