### ISSUE TITLE
Task relation keyboard shortcut doesn’t work after creating first task relation.

### ISSUE THREAD

**Issue by perfectra1n** [go-vikunja/frontend#122]
### Vikunja Frontend Version

0.21.0

### Vikunja API Version

0.21.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
The relations are already shown at that point. What should the shortcut do instead?

**Comment by perfectra1n** [comment]
Hi @kolaente,

Understood, fair point. However since this is what happens after hitting `r` on a new task:
![image](https://github.com/go-vikunja/frontend/assets/2390633/4f5e411a-0a39-4cc0-821d-45c1d5f3f203)


I was expecting this menu to open again after hitting `r` again, after assigning the first related task:
![image](https://github.com/go-vikunja/frontend/assets/2390633/30edb5fb-42ab-4f1c-b99e-58b1c12803ef)


Since `r` is more or less "unbound" at that point since relations are already open, perhaps rebinding it to open the "New Task Relation" window wouldn't be too harmful?

**Comment by kolaente** [comment]
Should be fixed with 5630c90dee647fedc6b937cc2fe46d0ddb2c24e4 - please check with the next unstable build if the solution works for you.
