### ISSUE TITLE
Wrong color of Card tittle when switching to Dark mode

### ISSUE THREAD

**Issue by hugosxm** [go-vikunja/frontend#135]
### Description

Hi, 

I just tried to color cards, and I found that when you switch theme from light to dark, it reverts color of the colored card, but this is not good, if you choose a yellow or white color you won't be able to read the tittle anymore : 

Dark mode :

![vikunja_dark](https://github.com/go-vikunja/frontend/assets/23743455/d9f67dda-1450-4334-9bd7-79d20d1e44a8)

Light mode :
![vikunja_light](https://github.com/go-vikunja/frontend/assets/23743455/a5f752ef-6a4b-44a5-8dd4-9d700500c4ad)

Dark mode should revert color of the tittle only for cards that are close to black and white I think.

Sorry if this is not clear ^^

### Vikunja Frontend Version

0.21.0

### Vikunja API Version

0.21.0

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Fixed in 34e4862c88904f114a36e65c851361b11443fadd. Please check with the next unstable build.

**Comment by hugosxm** [comment]
@kolaente  Yep ! Much better ! Thanks for the very quick fix !!

**Comment by hugosxm** [comment]
@kolaente sorry but i just saw this : 

![vikunja_card_color](https://github.com/go-vikunja/frontend/assets/23743455/02f92c68-c6b9-4032-8d75-9739a378d304)


Maybe we should fix all the text of the card and not just the tittle ...

**Comment by kolaente** [comment]
Pushed another fix in da311fce9ebe3261b74b2f159e01d00a1284133e - please check again with the next unstable build.

**Comment by hugosxm** [comment]
Seems the same to me, i used sha256:300eb43e01de4cec355bd197d2d62f8a872b55a088ee178a6a53cd2a757edf67 image, pushed two hours ago ? Am I on the right image to test ?

**Comment by kolaente** [comment]
@hugosxm which Vikunja version is that?

**Comment by hugosxm** [comment]
@kolaente  from the webui : Version : 0.22.0+68-c7b70844c6

**Comment by kolaente** [comment]
Seems to work fine for me. Can you share a screenshot and explain what you think is wrong?

**Comment by hugosxm** [comment]
I have exaclty the same behavior, like my screenshot 3 days ago, I tried to clean the cache, different browser... weird

**Comment by kolaente** [comment]
Pushed another fix for this in cd0149ef69a58e2c00e68541f3c26745fee218df. Please check again with the next unstable build (in ~45min)

**Comment by hugosxm** [comment]
I still see color mismatches, I tried all the predefined colors, the first one, the blue is not working by the way. 

Maybe I should try with a fresh install ? Each time I tested, I tested on my existing vikunja as I tought it is safe because it is the frontend part not the api part...

![vikunja_card_color](https://github.com/go-vikunja/frontend/assets/23743455/6ce02bed-3d63-4c97-9f46-50ef77d6c46a)

**Comment by kolaente** [comment]
Does it work on [try](https://try.vikunja.io)?

**Comment by hugosxm** [comment]
@kolaente  yes it works on the demo ! I forgot that vikunja have this public demo ...

But the blue color is not working on the demo too ^^

**Comment by kolaente** [comment]
@hugosxm The blue color issue should be fixed in  https://github.com/go-vikunja/frontend/commit/6cc75928d8ffd0ecf6ba082425e80bfff8519bbe
