### ISSUE TITLE
[Feature request] Allow reordering of tasks in "List" view

### ISSUE THREAD

**Issue by SteveDinn** [go-vikunja/frontend#18]
Much of the time, I don't want a full KanBan board, but I do want to control the order of items in my to-do list. It would be nice to be able to manually re-order the items in the "List" view. Maybe this should also re-order the items in the KanBan view relative to that task's bucket.

**Comment by SteveDinn** [comment]
Also, in the same vein, an option for "Add this task to the bottom of the list (instead of the top)".

**Comment by kolaente** [comment]
This is an often requested feature ([here](https://kolaente.dev/vikunja/frontend/issues/115)).
I have it on the roadmap, it will hopefully be included in the next release.

**Comment by kolaente** [comment]
Implemented in [#620](https://kolaente.dev/vikunja/frontend/pulls/620) and [#923](https://kolaente.dev/vikunja/api/pulls/923). A new unstable release containing the changes is already released, you can also test it on [try](https://try.vikunja.io).

Feel free to open a new issue or ping if you find something is not quite working.
