### ISSUE TITLE
[Bug] Update of list properties after change

### ISSUE THREAD

**Issue by mrlorx** [go-vikunja/frontend#21]
After changing the list properties (color and name), the change in the **Upcoming** and **Overview** view is only updated after a full page reload.
Only a small bug, but it still would be nice to see it fixed.
Btw: I'm very new to Vikunja, but I love it so far, keep up the excellent work!

**Comment by kolaente** [comment]
What version? Can you reproduce this on [try](https://try.vikunja.io)? There has been a similar bug which I've fixed recently.

**Comment by mrlorx** [comment]
I just updated to the newest version and this was already fixed. Thanks for the good work!
