### ISSUE TITLE
"Save" copy instead of "Done" for Description

### ISSUE THREAD

**Issue by jbd7** [go-vikunja/frontend#24]
Hey, I noticed a minor UX inconsistency today:
- While editing a task description on the List-view, the save button is called "Save" and has a blue background.
- While editing a task description on the Task-view, the save button is called "Done" and has a grey background.

There's also proximity with the green "Done" status button. By mistake I marked a task as Done instead of saving the description.

![image](https://user-images.githubusercontent.com/13196991/129921509-f4c1393d-8409-447d-ab98-0b36a0b629aa.png)

Suggestion: Keep the copy "Save" and the blue button background consistent through the frontend.

**Comment by kolaente** [comment]
There's been a bit of discussion about that lately: https://kolaente.dev/vikunja/frontend/issues/652

In comparison to the save button on the quick edit this one only saves the description whereas the done button only saves the description. In the latest unstable version the done button has been moved below the text, similar to the way it is solved in comments. Please check it out on try, what do you think?

**Comment by jbd7** [comment]
Thanks, I didn't see that. Btw, do you prefer threads on koalente.dev instead of github?

From the screenshots there the placement does look better. It'd indeed make sense to keep consistency with the "COMMENT" button just blow. When it comes to the copy, I think "Edit"/"Save" or "Edit"/"Update" is more common and understood than < Pencil-icon >/"Finish", taking as an example this very github page :) 
![image](https://user-images.githubusercontent.com/13196991/129925500-460593f6-7b04-4066-96ee-ca94e6882406.png)

**Comment by kolaente** [comment]
Threads on Gitea or here are both fine for me. The majority of the active development happens the Gitea instance though.

I agree with you about the wording, will put something up.
