### ISSUE TITLE
Case Insensitivity When Searching for Assignees

### ISSUE THREAD

**Issue by DieGurke** [go-vikunja/frontend#29]
Currently the exact user name has to be typed into the assign user field.
It would be much more intuitive and beneficial for the workflow, if this field was case insensitive.

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/api/commit/c076f73a87bc9b39b17389e25d0186ab71aa24bf - please check with the next unstable build if the problem went away.
