### ISSUE TITLE
Filter bar scroll bug

### ISSUE THREAD

**Issue by Noah231515** [go-vikunja/frontend#42]
![image](https://user-images.githubusercontent.com/44912201/155861127-c310ef59-b4e1-4f41-9bcc-982708ee5374.png)

Steps to reproduce:
1. Navigate to any any List, Gaant, Table or Kanban screen
2. Click filter bar
3. The entire screen itself extends with blank white space

Perhaps the filter bar itself should be only as tall as the page with a scroll?

**Comment by kolaente** [comment]
What version are you using? Can you reproduce this on https://try.vikunja.io?

**Comment by kolaente** [comment]
I can reproduce the problem with the filter popup, but not the top header.

![image](https://user-images.githubusercontent.com/13721712/155886347-42232a11-8aec-4de4-a78b-ebb63171f1fb.png)

What browser and version did you use?

**Comment by kolaente** [comment]
I'll take another look at this after https://kolaente.dev/vikunja/frontend/pulls/1342 is merged as it does a few changes to the filter popup.

**Comment by Noah231515** [comment]
> I can reproduce the problem with the filter popup, but not the top header.
> 
> ![image](https://user-images.githubusercontent.com/13721712/155886347-42232a11-8aec-4de4-a78b-ebb63171f1fb.png)
> 
> What browser and version did you use?

This was on Firefox 97. I haven't been able to reproduce the header going wild either.

**Comment by dpschen** [comment]
@kolaente I guess this can be fixed.
