### ISSUE TITLE
Notifications & 401

### ISSUE THREAD

**Issue by tamaskan** [go-vikunja/frontend#47]
Hi, i have a strange issue:

Frontend: 0.18.2
Api: 0.18.1

Usually after a few days i get the constant "invalid or expired jwt"-Message from /api/v1/notifications on Firefox. Everything else works and uses the new token, but this request keeps using the expired one.

**Comment by kolaente** [comment]
If you log out and back in again, does it work?

**Comment by tamaskan** [comment]
i usually refresh the page and everything works again, but i will try the demo-installation

**Comment by tamaskan** [comment]
![vikunja](https://user-images.githubusercontent.com/3661769/164714697-0b67052b-47fc-431c-9aa2-f7f44521ef93.png)

Tried it with the demo-installation and it's the same result. Does the window need to be in focus ? I just have a new browser-window on another monitor and don't interact with it.

**Comment by kolaente** [comment]
It should refresh the session every time you bring the window in focus and it is about to expire. It looks like the notification polling does not use the refreshed session.

**Comment by tamaskan** [comment]
it won't be an issue for me when the new version comes out and i can set a multiple year long jwt. 
i don't know if other people are using it like i do, but it shouldn't be an issue for the vast majority of users.

**Comment by kolaente** [comment]
Should be fixed in 3e7f598ee8858b201f7c4492e2fb3aa78ba782ea - please verify on try if it is solved. Feel free to ping if you have other issues or it still does not work.
