### ISSUE TITLE
Mobile page to right meue dies not work

### ISSUE THREAD

**Issue by hackschnitzel09** [go-vikunja/frontend#52]
Hey,
I run the latest unstable in docker which is updated daily. Ony android phone the menue next to the avatar does not work. It opens but notvin the front so not usable. After the api update I can not log out and in again. Thanks for the awesome work!!
Regards:)

**Comment by kolaente** [comment]
Should be fixed in 90bb80034693408bb950c10439963ec82aca87a1 - please check in ~30 min with the latest unstable release or on [try](https://try.vikunja.io) if your issue is resolved.
