### ISSUE TITLE
Render image attachments on card (kanban view)

### ISSUE THREAD

**Issue by throwabird** [go-vikunja/frontend#53]
I think it would be nice to have the attachments render on the card view of the kanban board (similar to trello).
To decide which of the attachments is chosen the user should probably be able to "make primary" an image or something simmilar.
This would also allow uploading attachments without this feature and wouldn't change the behavior for users not interested in this feature.

![image](https://user-images.githubusercontent.com/88376487/169980140-44788f0e-1307-4563-be0f-30603fbf36d1.png)

**Comment by kolaente** [comment]
How would that work? Uploading an attachment and then being able to select it as the header? Or selecting a title image separately (the way trello does it)?

**Comment by throwabird** [comment]
I mean being able to select a cover image (as trello calls it) or header (as you called it) from the attachments. AFAIK trello does it like that aswell, you just choose a cover from your attachments and don't need to upload a cover separately.
![image](https://user-images.githubusercontent.com/88376487/170684320-fa758d14-92ac-4ad5-a541-3138345be974.png)
![image](https://user-images.githubusercontent.com/88376487/170684692-09f77340-31f7-4cc3-89cc-795e53e7c7c6.png)

**Comment by kolaente** [comment]
Awesome, thanks for the explanation. I've added this to the backlog.

**Comment by dpschen** [comment]
Love the visualisation! :)

**Comment by dpschen** [comment]
This was implemented in https://kolaente.dev/vikunja/frontend/pulls/2460

Looking at the inspiration images above:
We are still missing an inline preview for attached images.

@kolaente: Would you consider this a new ticket?

**Comment by kolaente** [comment]
@dpschen Yeah inline preview is a new task.
