### ISSUE TITLE
Adding start date automatically adds the end date causing sync error

### ISSUE THREAD

**Issue by mzfr** [go-vikunja/frontend#55]
So I'm not sure why this was added but if I add "Start date" to the task then "end date" is added.

Now it would have been fine, but I noticed that if a task has an "End date" property, Davx^5 App throws an error stating "received an invalid task from server". When I removed that property it was able to sync fine.

**Comment by kolaente** [comment]
If the task has a due date defined and you define a start date without defining an end date it will automatically use the due date as end date. You should be able to manually remove it though.

Do you have any logs from either the api server or DavX⁵?

**Comment by kolaente** [comment]
Looks like this is the problem:

```
DURATION:PT24.000000H1440.000000M86400.000000S
```

That duration looks way of.
