### ISSUE TITLE
After modifying the name of a namespace, it has no lists (until refresh)

### ISSUE THREAD

**Issue by canadaduane** [go-vikunja/frontend#58]
On the left-hand panel, I can click the "..." button to see a menu of actions on a namespace. I choose "Edit" and change the name of the namespace. When I return, the lists under that namespace are gone and it says `(0)` as the count.

Before:
![image](https://user-images.githubusercontent.com/129/172949881-4ac48a32-2aa2-4157-a550-d1807ac6fdf5.png)

After:
![image](https://user-images.githubusercontent.com/129/172949926-4b8126c1-7e70-4d3b-baa6-0e73b8312917.png)

Refreshing the page restores the lists to the newly renamed namespace. (In other words, this is only a bug that causes fear in the heart of the user, but does not actually do harm).

**Comment by kolaente** [comment]
Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by canadaduane** [comment]
On the `try` server, I get a different result: the name changes and the list remains, but there is an error message along with a success message:

![image](https://user-images.githubusercontent.com/129/173191733-29775701-fe9b-4407-b5f6-e1e2c8a641a0.png)

**Comment by kolaente** [comment]
That bug should be fixed with aadf75c7bffc3ffc5367d7a126905b7a3f8b4a1c.
