### ISSUE TITLE
Next tagged release?

### ISSUE THREAD

**Issue by canadaduane** [go-vikunja/frontend#61]
We're using vikunja on a Clouron host and they only update when a new tag is released. (We're also sponsoring this project, thank you!)

I'm curious when the next release might be? Based on my past couple of bug reports, it's clear you've come a long way since 0.18.2 and several things have been fixed or have improved.

**Comment by kolaente** [comment]
Thanks for sponsoring!

I hope to get a new release out in the next few weeks, rather sooner than later - I said this a few times in the last few months though so yeah. At this point it's pretty much bug fixing only to get it ready but I keep finding new bugs.

**Comment by kolaente** [comment]
There is a new release: https://vikunja.io/blog/2022/08/whats-new-in-vikunja-0.19.0/
