### ISSUE TITLE
Let user edit only 1 card in the list

### ISSUE THREAD

**Issue by tio-trom** [go-vikunja/frontend#62]
I would expect that if I assign a card to a user, the user can automatically edit that card/task. But it seems not to be the case. So is there a way to only share a card/task with a user and give the user edit permission?

**Comment by kolaente** [comment]
Users will only be able to edit a task if you give them at least write access to the list. Assignees are a different concept, they only show who should be responsible for a task.

**Comment by tio-trom** [comment]
But if you give them write access to the list it means they can edit any card/task in the list?

**Comment by dpschen** [comment]
If I get it correctly: the problem might come from the fact that you can assign a user to a task that doesn’t have write access to the list. Maybe that is something that should change? 🤔

**Comment by tio-trom** [comment]
Yeah I would like to be able to give access to a task, and to a task only. Not to the entire list. This can be very helpful. The user can have read access to the list, but only write access to a task that he/she is assigned to.

**Comment by kolaente** [comment]
> But if you give them write access to the list it means they can edit any card/task in the list?

Yes.

I think this issue could be turned into a feature so that it behaves as you expected but it should be an option in the list's settings.
