### ISSUE TITLE
small bug: "last seen" is not cleared on log out

### ISSUE THREAD

**Issue by mtettke123** [go-vikunja/frontend#70]
Funny small bug: If one user logs out and another user logs in, the second user sees the "last seen" section from the first user - regardless if the second user has access to the lists or not.

**Comment by kolaente** [comment]
Fixed in 51ffe930483bdd02118b512bb00a1ca50a5ce2e5 - please check with the next unstable build in ~30 min if the problem went away.

**Comment by mtettke123** [comment]
Can confirm is fixed. "last seen" is now always empty on login, what is sad in some other way...

**Comment by dpschen** [comment]
This also affects the selected list view: https://kolaente.dev/vikunja/frontend/issues/2247
