### ISSUE TITLE
Automatically redirects if only one Oauth provider

### ISSUE THREAD

**Issue by thelicato** [go-vikunja/frontend#90]
### Description

Currently if there is only one Oauth provider it automatically "clicks" on the "Login with <provider>" button. This is especially awkward when you logout and it **automatically re-performs the login**.

### Vikunja Frontend Version

0.20.1

### Vikunja API Version

0.20.1

### Browser and version

Chrome Version 107.0.5304.110 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
This is meant for cases where you open Vikunja from an external source (like a dashboard) and would want to get logged in right away.

What would you propose as a solution to that problem?

**Comment by thelicato** [comment]
Well I think that the normal usage is that the user **must** click on the OpenID provider login button. It doesn't make sense this way, it is also impossible to fully logout in a normal way.

**Comment by kolaente** [comment]
With https://github.com/go-vikunja/frontend/commit/3891d5b87634c890265477680fafaa04ff06cc3e there's now an extra query parameter to automatically redirect. This allows for automatically logging in when opening Vikunja from an external dashboard but prevents automatically re-logging the user in after being logged out.
