### ISSUE TITLE
frontend would not start up anymore (docker on pi4)

### ISSUE THREAD

**Issue by smignon612** [go-vikunja/frontend#99]
### Description

after upgrade to the latest version, frontend was unable to start up, 0.19 works fun

### Vikunja Frontend Version

latest

### Vikunja API Version

latest

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
Any errors? Does the unstable frontend work?

**Comment by smignon612** [comment]
the docker just would not start up, the api works fine. this is the error in the docker log: exec /docker-entrypoint.sh: exec format error. maybe missing shebang?

**Comment by kolaente** [comment]
This is probably related to missing docker images for arm which has been fixed in the meantime. Please try with the last release (`latest` should work)

**Comment by smignon612** [comment]
its ok now
